CREATE TABLE [dbo].[ATTI_DOCUMENTI_Audit] (
    [IdATTI_DOCUMENTI_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [Uid] UNIQUEIDENTIFIER NOT NULL,
    [UIDAtto] UNIQUEIDENTIFIER NULL,
    [Tipo] INT NULL,
    [Data] DATETIME NULL,
    [Path] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Titolo] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Pubblica] BIT NULL,
    [UIDUtenteModifica] UNIQUEIDENTIFIER NULL,
    [DataModifica] DATETIME NULL,
    [Eliminato] BIT NOT NULL,
    CONSTRAINT [PK_ATTI_DOCUMENTI_Audit] PRIMARY KEY ([IdATTI_DOCUMENTI_Audit])
);