CREATE TABLE [dbo].[ATTI_Audit] (
    [IdATTI_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [UIDAtto] UNIQUEIDENTIFIER NOT NULL,
    [NAtto] VARCHAR(255) COLLATE Latin1_General_CI_AI NOT NULL,
    [IDTipoAtto] INT NOT NULL,
    [Oggetto] VARCHAR(500) COLLATE Latin1_General_CI_AI NULL,
    [Note] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Path_Testo_Atto] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [UIDSeduta] UNIQUEIDENTIFIER NULL,
    [Data_apertura] DATETIME NULL,
    [Data_chiusura] DATETIME NULL,
    [VIS_Mis_Prog] BIT NOT NULL,
    [UIDAssessoreRiferimento] UNIQUEIDENTIFIER NULL,
    [Notifica_deposito_differita] BIT NOT NULL,
    [OrdinePresentazione] BIT NULL,
    [OrdineVotazione] BIT NULL,
    [Priorita] INT NULL,
    [DataCreazione] DATETIME NULL,
    [UIDPersonaCreazione] UNIQUEIDENTIFIER NULL,
    [DataModifica] DATETIME NULL,
    [UIDPersonaModifica] UNIQUEIDENTIFIER NULL,
    [Eliminato] BIT NULL,
    [LinkFascicoloPresentazione] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [DataCreazionePresentazione] DATETIME NULL,
    [LinkFascicoloVotazione] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [DataCreazioneVotazione] DATETIME NULL,
    [DataUltimaModificaEM] DATETIME NULL,
    [BloccoEM] BIT NOT NULL,
    [BloccoODG] BIT NOT NULL,
    [Jolly] BIT NOT NULL,
    [Emendabile] BIT NOT NULL,
    [Fascicoli_Da_Aggiornare] BIT NOT NULL,
    [Legislatura] INT NULL,
    [Invio_Notifiche_Deposito_Solo_UOLA] BIT NOT NULL,
    CONSTRAINT [PK_ATTI_Audit] PRIMARY KEY ([IdATTI_Audit])
);