CREATE TABLE [dbo].[ATTI_DASI_Audit] (
    [IdATTI_DASI_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [UIDAtto] UNIQUEIDENTIFIER NOT NULL,
    [Tipo] INT NULL,
    [TipoMOZ] INT NULL,
    [Progressivo] INT NULL,
    [Etichetta] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [NAtto] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [NAtto_search] INT NULL,
    [Oggetto] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Oggetto_Modificato] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Oggetto_Approvato] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Premesse] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Premesse_Modificato] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [TipoRichiesta] INT NULL,
    [TipoRichiestaDestinatario] INT NULL,
    [Richiesta] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Richiesta_Modificata] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [DataCreazione] DATETIME NULL,
    [UIDPersonaCreazione] UNIQUEIDENTIFIER NULL,
    [idRuoloCreazione] INT NULL,
    [DataModifica] DATETIME NULL,
    [UIDPersonaModifica] UNIQUEIDENTIFIER NULL,
    [DataPresentazione] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [DataPresentazione_MOZ] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [DataPresentazione_MOZ_URGENTE] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [DataPresentazione_MOZ_ABBINATA] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [UIDPersonaPresentazione] UNIQUEIDENTIFIER NULL,
    [DataRichiestaIscrizioneSeduta] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [UIDPersonaRichiestaIscrizione] UNIQUEIDENTIFIER NULL,
    [UIDPersonaProponente] UNIQUEIDENTIFIER NULL,
    [UIDPersonaPrimaFirma] UNIQUEIDENTIFIER NULL,
    [DataPrimaFirma] DATETIME NULL,
    [Proietta] BIT NULL,
    [DataProietta] DATETIME NULL,
    [UIDPersonaProietta] UNIQUEIDENTIFIER NULL,
    [DataRitiro] DATETIME NULL,
    [UIDPersonaRitiro] UNIQUEIDENTIFIER NULL,
    [Hash] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [IDTipo_Risposta] INT NULL,
    [OrdineVisualizzazione] INT NULL,
    [PATH_AllegatoGenerico] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Note_Pubbliche] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Note_Private] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [IDStato] INT NULL,
    [Firma_su_invito] BIT NULL,
    [UID_QRCode] UNIQUEIDENTIFIER NULL,
    [AreaPolitica] INT NULL,
    [id_gruppo] INT NULL,
    [Eliminato] BIT NULL,
    [UIDPersonaElimina] UNIQUEIDENTIFIER NULL,
    [DataElimina] DATETIME NULL,
    [chkf] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [Timestamp] DATETIME NULL,
    [Atto_Certificato] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Legislatura] INT NULL,
    [UIDSeduta] UNIQUEIDENTIFIER NULL,
    [DataIscrizioneSeduta] DATETIME NULL,
    [UIDPersonaIscrizioneSeduta] UNIQUEIDENTIFIER NULL,
    [UID_MOZ_Abbinata] UNIQUEIDENTIFIER NULL,
    [UID_Atto_ODG] UNIQUEIDENTIFIER NULL,
    [Non_Passaggio_In_Esame] BIT NULL,
    [Inviato_Al_Protocollo] BIT NULL,
    [DataInvioAlProtocollo] DATETIME NULL,
    [CapogruppoNeiTermini] BIT NULL,
    [MOZU_Capigruppo] BIT NULL,
    [FirmeCartacee] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [DataAnnunzio] DATETIME NULL,
    [Protocollo] VARCHAR(150) COLLATE Latin1_General_CI_AI NULL,
    [CodiceMateria] VARCHAR(150) COLLATE Latin1_General_CI_AI NULL,
    [Pubblicato] BIT NULL,
    [Sollecito] BIT NULL,
    [IDTipo_Risposta_Effettiva] INT NULL,
    [TipoChiusuraIter] INT NULL,
    [DataChiusuraIter] DATETIME NULL,
    [NoteChiusuraIter] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [Emendato] BIT NULL,
    [TipoVotazioneIter] INT NULL,
    [AreaTematica] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [AltriSoggetti] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [DCR] INT NULL,
    [DCCR] INT NULL,
    [DCRL] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [BURL] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [Privacy_Dati_Personali_Giudiziari] BIT NULL,
    [Privacy_Divieto_Pubblicazione_Salute] BIT NULL,
    [Privacy_Divieto_Pubblicazione_Vita_Sessuale] BIT NULL,
    [Privacy_Divieto_Pubblicazione] BIT NULL,
    [Privacy_Dati_Personali_Sensibili] BIT NULL,
    [Privacy_Divieto_Pubblicazione_Altri] BIT NULL,
    [Privacy_Dati_Personali_Semplici] BIT NULL,
    [Privacy] BIT NULL,
    [DataComunicazioneAssemblea] DATETIME NULL,
    [ImpegniScadenze] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [StatoAttuazione] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [CompetenzaMonitoraggio] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [MonitoraggioConcluso] BIT NULL,
    [DataTrasmissioneMonitoraggio] DATETIME NULL,
    [IterMultiplo] BIT NULL,
    [UIDPersonaRelatore1] UNIQUEIDENTIFIER NULL,
    [UIDPersonaRelatore2] UNIQUEIDENTIFIER NULL,
    [UIDPersonaRelatoreMinoranza] UNIQUEIDENTIFIER NULL,
    [TipoChiusuraIterCommissione] INT NULL,
    [DataChiusuraIterCommissione] DATETIME NULL,
    [TipoVotazioneIterCommissione] INT NULL,
    [RisultatoVotazioneIterCommissione] INT NULL,
    [DataSedutaRisposta] DATETIME NULL,
    [DataComunicazioneAssembleaRisposta] DATETIME NULL,
    [DataProposta] DATETIME NULL,
    [DataTrasmissione] DATETIME NULL,
    [FlussoRespingi] BIT NULL,
    [UIDPersonaFlussoRespingi] UNIQUEIDENTIFIER NULL,
    [DataFlussoRespingi] DATETIME NULL,
    [Ritardo] INT NULL,
	[VersioneStampa] [int] NOT NULL,
	[DataUltimaStampa] [datetime] NULL,
	[PathStampa] [varchar](max) NULL,
	[StampaValida] [bit] NOT NULL,
	[NascondiGruppo] [bit] NOT NULL,
    CONSTRAINT [PK_ATTI_DASI_Audit] PRIMARY KEY ([IdATTI_DASI_Audit])
);
