CREATE TABLE [dbo].[EM_Audit] (
    [IdEM_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [UIDEM] UNIQUEIDENTIFIER NOT NULL,
    [Progressivo] INT NULL,
    [UIDAtto] UNIQUEIDENTIFIER NOT NULL,
    [N_EM] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [id_gruppo] INT NOT NULL,
    [Rif_UIDEM] UNIQUEIDENTIFIER NULL,
    [N_SUBEM] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [SubProgressivo] INT NULL,
    [UIDPersonaProponente] UNIQUEIDENTIFIER NULL,
    [UIDPersonaProponenteOLD] UNIQUEIDENTIFIER NULL,
    [DataCreazione] DATETIME NULL,
    [UIDPersonaCreazione] UNIQUEIDENTIFIER NULL,
    [idRuoloCreazione] INT NULL,
    [DataModifica] DATETIME NULL,
    [UIDPersonaModifica] UNIQUEIDENTIFIER NULL,
    [DataDeposito] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [UIDPersonaPrimaFirma] UNIQUEIDENTIFIER NULL,
    [DataPrimaFirma] DATETIME NULL,
    [UIDPersonaDeposito] UNIQUEIDENTIFIER NULL,
    [Proietta] BIT NOT NULL,
    [DataProietta] DATETIME NULL,
    [UIDPersonaProietta] UNIQUEIDENTIFIER NULL,
    [DataRitiro] DATETIME NULL,
    [UIDPersonaRitiro] UNIQUEIDENTIFIER NULL,
    [Hash] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [IDTipo_EM] INT NOT NULL,
    [IDParte] INT NOT NULL,
    [NTitolo] VARCHAR(5) COLLATE Latin1_General_CI_AI NULL,
    [NCapo] VARCHAR(5) COLLATE Latin1_General_CI_AI NULL,
    [UIDArticolo] UNIQUEIDENTIFIER NULL,
    [UIDComma] UNIQUEIDENTIFIER NULL,
    [UIDLettera] UNIQUEIDENTIFIER NULL,
    [NLettera] VARCHAR(5) COLLATE Latin1_General_CI_AI NULL,
    [UIDParte_LR] UNIQUEIDENTIFIER NULL,
    [NNumero] VARCHAR(5) COLLATE Latin1_General_CI_AI NULL,
    [UIDMissione] UNIQUEIDENTIFIER NULL,
    [NMissione] INT NULL,
    [NProgramma] INT NULL,
    [NTitoloB] INT NULL,
    [OrdinePresentazione] INT NOT NULL,
    [OrdineVotazione] INT NOT NULL,
    [TestoEM_originale] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [EM_Certificato] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [TestoREL_originale] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [PATH_AllegatoGenerico] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [PATH_AllegatoTecnico] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [EffettiFinanziari] INT NULL,
    [NOTE_EM] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [NOTE_Griglia] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [TestoEM_Modificabile] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [IDStato] INT NULL,
    [Firma_su_invito] BIT NOT NULL,
    [UID_QRCode] UNIQUEIDENTIFIER NOT NULL,
    [AreaPolitica] INT NULL,
    [Eliminato] BIT NOT NULL,
    [UIDPersonaElimina] UNIQUEIDENTIFIER NULL,
    [DataElimina] DATETIME NULL,
    [chkf] VARCHAR(255) COLLATE Latin1_General_CI_AI NULL,
    [chkem] INT NULL,
    [Timestamp] DATETIME NULL,
    [Colore] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [Tags] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [VersioneStampa] INT NOT NULL,
    [DataUltimaStampa] DATETIME NULL,
    [PathStampa] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [StampaValida] BIT NOT NULL,
    CONSTRAINT [PK_EM_Audit] PRIMARY KEY ([IdEM_Audit])
);