CREATE TABLE [dbo].[SEDUTE_Audit] (
    [IdSEDUTE_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [UIDSeduta] UNIQUEIDENTIFIER NOT NULL,
    [Data_seduta] DATETIME NOT NULL,
    [Data_apertura] DATETIME NULL,
    [Data_effettiva_inizio] DATETIME NULL,
    [Data_effettiva_fine] DATETIME NULL,
    [IDOrgano] INT NULL,
    [Scadenza_presentazione] DATETIME NULL,
    [DataScadenzaPresentazioneIQT] DATETIME NULL,
    [DataScadenzaPresentazioneMOZ] DATETIME NULL,
    [DataScadenzaPresentazioneMOZA] DATETIME NULL,
    [DataScadenzaPresentazioneMOZU] DATETIME NULL,
    [DataScadenzaPresentazioneODG] DATETIME NULL,
    [id_legislatura] INT NULL,
    [Intervalli] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [UIDPersonaCreazione] UNIQUEIDENTIFIER NULL,
    [DataCreazione] DATETIME NULL,
    [UIDPersonaModifica] UNIQUEIDENTIFIER NULL,
    [DataModifica] DATETIME NULL,
    [Eliminato] BIT NULL,
    [Riservato_DASI] BIT NOT NULL,
    [Riservato_DASI_MOZ] BIT NOT NULL,
    [Riservato_DASI_IQT] BIT NOT NULL,
    [Blocco_MOZ_Abbinate] BIT NOT NULL,
    [Note] VARCHAR(150) COLLATE Latin1_General_CI_AI NULL,
    CONSTRAINT [PK_SEDUTE_Audit] PRIMARY KEY ([IdSEDUTE_Audit])
);