CREATE TABLE [dbo].[UTENTI_NoCons_Audit] (
    [IdUTENTI_NoCons_Audit] INT NOT NULL IDENTITY(1,1),
    [DatAudit] DATETIME NOT NULL,
    [UteAudit] UNIQUEIDENTIFIER NULL,
    [UID_persona] UNIQUEIDENTIFIER NOT NULL,
    [id_persona] INT NOT NULL,
    [cognome] VARCHAR(50) COLLATE Latin1_General_CI_AI NOT NULL,
    [nome] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [email] VARCHAR(250) COLLATE Latin1_General_CI_AI NULL,
    [foto] VARCHAR(250) COLLATE Latin1_General_CI_AI NULL,
    [UserAD] VARCHAR(50) COLLATE Latin1_General_CI_AI NULL,
    [id_gruppo_politico_rif] INT NULL,
    [notifica_firma] BIT NOT NULL,
    [notifica_deposito] BIT NOT NULL,
    [RichiediModificaPWD] BIT NOT NULL,
    [Data_ultima_modifica_PWD] DATETIME NULL,
    [pass_locale_crypt] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [gruppi_autorizzazione] VARCHAR(MAX) COLLATE Latin1_General_CI_AI NULL,
    [attivo] BIT NOT NULL,
    [deleted] BIT NOT NULL,
    [UIDUtenteModifica] UNIQUEIDENTIFIER NULL,
    [DataModifica] DATETIME NULL,
    CONSTRAINT [PK_UTENTI_NoCons_Audit] PRIMARY KEY ([IdUTENTI_NoCons_Audit])
);